INSERT INTO `faculties` (`FACULTYID`, `FACULTYNAME`, `FACULTYNAMEENG`) VALUES
( 2, 'คณะวิทยาศาสตร์', 'Science'),
( 3, 'คณะเกษตรศาสตร์', 'Agriculture'),
( 4, 'คณะวิศวกรรมศาสตร์', 'Engineering'),
( 5, 'คณะศึกษาศาสตร์', 'Education'),
( 6, 'คณะพยาบาลศาสตร์', 'Nursing'),
( 7, 'คณะแพทยศาสตร์', 'Medicine'),
( 8, 'คณะมนุษยศาสตร์และสังคมศาสตร์', 'Humanities and Social Sciences'),
( 9, 'คณะเทคนิคการแพทย์', 'Associated Medical Sciences'),
( 10, 'บัณฑิตวิทยาลัย', 'Graduate School'),
( 11, 'คณะสาธารณสุขศาสตร์', 'Public Health'),
( 13, 'คณะทันตแพทยศาสตร์', 'Dentistry'),
( 15, 'คณะเภสัชศาสตร์', 'Pharmaceutical Sciences'),
( 16, 'คณะเทคโนโลยี', 'Technology'),
( 18, 'คณะสัตวแพทยศาสตร์', 'Veterinary Medicine'),
( 20, 'คณะสถาปัตยกรรมศาสตร์', 'Architecture'),
( 21, 'คณะบริหารธุรกิจและการบัญชี', 'Business Administration and Accountancy'),
( 22, 'คณะศิลปกรรมศาสตร์', 'Fine and Applied Arts'),
( 23, 'วิทยาเขตหนองคาย', 'Nong Khai Campus'),
( 27, 'คณะนิติศาสตร์', 'Law'),
( 28, 'วิทยาลัยการปกครองท้องถิ่น', 'College of Local Administration'),
( 29, 'วิทยาลัยนานาชาติ', 'International College'),
( 32, 'คณะเศรษฐศาสตร์', 'Economics'),
( 33, 'คณะวิทยาการจัดการ', 'Management Sciences'),
( 41, 'คณะวิทยาศาสตร์ประยุกต์และวิศวกรรมศาสตร์ วิทยาเขตหนองคาย', 'Applied Science and Engineering'),
( 42, 'คณะสังคมศาสตร์บูรณาการ วิทยาเขตหนองคาย', 'Integrated Social Sciences'),
( 43, 'คณะบริหารธุรกิจ วิทยาเขตหนองคาย', 'Business Administration'),
( 44, 'คณะศิลปศาสตร์ วิทยาเขตหนองคาย', 'Liberal Atrs'),
( 51, 'สำนักวิชาศึกษาทั่วไป', 'General Education'),
( 53, 'สถาบันภาษา', null),
( 55, 'สมาคมศิษย์เก่า', 'KKU Alumni'),
( 74, 'วิทยาลัยบัณฑิตศึกษาการจัดการ', 'College of Graduate Study in Management');
